### ISSUE TITLE
CLAs are not acknowledged

### ISSUE THREAD

**Issue by khm** [cncf/cla#2]
Hello,

I sent a signed organizational CLA to the email address provided (cla@cncf.io) on 8 March 2017 and it has, so far, gone unacknowledge.  

Is there more action required on my part to get this CLA accepted?  If so, please let me know what that action is.

**Comment by caniszczyk** [comment]
@khm you're welcome to send it to cra@linuxfoundation.org also

We prefer you use the e-sign version as much as possible as manually it takes a bit longer: https://identity.linuxfoundation.org/projects/cncf

**Comment by khm** [comment]
Thanks, I'll send it there as well.  Is 'cra' the proper username component in that email address, or is that a typo for 'cla'?

In addition, I appreciate that the electronic version is more streamlined, but our legal team much prefers regular old documents.

**Comment by caniszczyk** [comment]
@khm np, it's cra, I found your CLA though and formally invited you as an org admin to the CNCF CLA system. You should have received an email for it and be able to use the management interface. Let me know if that worked.
