### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by lfrancke** [cncf/cla#5]
It's not 100% necessary but currently, the CLAs do not have a license. For anyone who'd want to reuse them, it'd be great if one could be added.

**Comment by lfrancke** [comment]
The CNCF CLA is mostly copied from Apache and they added this to their FAQ recently: https://www.apache.org/foundation/license-faq.html#CLA-Usage

Might be worth doing the same here.

**Comment by caniszczyk** [comment]
Sorry I missed the LICENSE in the repo, that's an oversight: https://github.com/cncf/cla/commit/e399091da4c29a7f14867b678617798aa4e9b64c

The CNCF IP Policy is specified in the charter: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
